### ISSUE TITLE
Bug 

### ISSUE THREAD

**Issue by rubencmu** [bd2kccd/py-causal#16]
Hi, also from the CCD help desk they report the next bug using py-causal.

"BTW, there's some bugs in stop_vm/start_vm, as in you can't stop and restart to clear memory."

Any ideas ?

Thanks

Ruben

**Comment by chirayukong** [comment]
That's a bug from the Javabridge project. I'll check with them about it.

**Comment by chirayukong** [comment]
@LeeKamentsky how should we clear memory on the java-bridge? It seems stop_vm/start_vm doesn't make the thing.

**Comment by LeeKamentsky** [comment]
This is a problem with the Java JVM. It can be started at most one time per process. Unfortunately, you can't shut the Javabridge down and then restart it again - you'll have to figure out how to handle its lifetime so that it starts at most once and shuts down at the end of the process.

Sorry that I can't give you a more helpful answer, but it's not under my control.

**Comment by rubencmu** [comment]
Thanks @LeeKamentsky. I will paste your answer to the user at the help desk.

Ruben
